services:
  mysql:
    image: mysql:8.0
    container_name: metahive-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: metahive
      MYSQL_USER: metahive_user
      MYSQL_PASSWORD: metahive_password
    ports:
      - "3070:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - metahive-network

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.1
    command:
      - "start-dev"
      - "--import-realm"
      - "--health-enabled=true"
    environment:
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://metahive-mysql:3306/metahive
      KC_DB_USERNAME: metahive_user
      KC_DB_PASSWORD: metahive_password
      KC_HTTP_PORT: 8181
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8181:8181"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - metahive-network

networks:
  metahive-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
