name: SonarCloud Analysis

on:
  push:
    branches:
      - main # Analyze commits pushed to main
  pull_request:
    types: [opened, synchronize, reopened] # Analyze pull requests

permissions:
  contents: read
  pull-requests: read # Allow reading PR details

jobs:
  build-and-analyze:
    name: Build, Test, and Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Crucial for SonarCloud branch/PR analysis

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make gradlew executable in backend
        # Only need to make the root gradlew executable
        run: chmod +x project/backend/gradlew

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          # Cache is relative to the runner workspace root
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('project/backend/**/build.gradle', 'project/backend/**/settings.gradle', 'project/backend/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build, Run Tests and Generate JaCoCo Reports
        working-directory: ./project/backend # Run gradle from the backend root
        # 'build' task usually depends on 'test', which triggers jacocoTestReport
        # --continue allows analysis even if some tests fail
        run: ./gradlew build --continue --info

      - name: SonarCloud Scan
        # Run even if the build step had test failures (--continue)
        if: success() || failure()
        uses: SonarSource/sonarcloud-github-action@v2.2.0
        with:
          # Set the base directory for the Sonar analysis (where gradlew is)
          projectBaseDir: project/backend
          # args: > # No args needed here! Plugin gets config from build.gradle/properties
            # -Dsonar.projectKey=... # Define in build.gradle or gradle.properties
            # -Dsonar.organization=... # Define in build.gradle or gradle.properties
            # -Dsonar.host.url=https://sonarcloud.io # Define in build.gradle or gradle.properties
        env:
          # Define the SonarCloud token in your GitHub repository secrets
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          # GITHUB_TOKEN is automatically provided by Actions, required for PR decoration
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}