name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and Analyze Maven Project
        run: |
          echo "Building and analyzing Maven project..."
          mvn clean verify sonar:sonar \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -DskipTests=true # Or remove if you want Maven to run its tests
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Make Gradle files executable
        run: |
          echo "Making Gradle files executable..."
          chmod +x project/backend/**/gradlew

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('project/backend/**/build.gradle', 'project/backend/**/gradle-wrapper.properties', 'project/backend/settings.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run Tests and Generate JaCoCo Reports (Gradle Modules)
        run: |
          echo "Running tests and generating JaCoCo reports for Gradle modules..."
          ./gradlew test jacocoTestReport --info --continue

      - name: SonarCloud Scan (Gradle)
        run: |
          echo "Running SonarCloud analysis for Gradle projects..."
          ./gradlew sonarqube \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
