receivers:
  otlp:
    protocols:
      # grpc: # You might have this defined, even if not used by the app currently
      #   endpoint: "0.0.0.0:4317"
      http: # Your app is sending here
        endpoint: "0.0.0.0:4318"

exporters:
  debug: # Keep for debugging if you want
    verbosity: detailed

  zipkin: # Add the Zipkin exporter configuration
    endpoint: "http://zipkin:9411/api/v2/spans" # Collector talks to zipkin container name
    # format: proto # Zipkin supports proto too, 'json' is default if omitted

processors:
  batch: # Optional but recommended for production

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch] # Optional: Add batch processor
      exporters: [debug, zipkin] # Add 'zipkin' to the exporters list
    metrics:
      receivers: [otlp]
      processors: [batch] # Optional
      exporters: [debug] # Keep exporting metrics to debug for now
    logs:
      receivers: [otlp]
      processors: [batch] # Optional
      exporters: [debug] # Keep exporting logs to debug for now