# No version needed

services:
  app:
    build: .
    container_name: project-manager-app # Unique name, matches target in prometheus.yml
    ports:
      - "9087:9087" # Map host port to container port
    environment:
      # Point to the SHARED collector using its container name
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_SERVICE_NAME=project-manager
      # Database connection (assuming DB is accessible on host machine's port 3306)
      - DB_URL=jdbc:mysql://host.docker.internal:3306/metadocs
      - DB_USERNAME=root
      - DB_PASSWORD=1234
    networks:
      - monitoring_net # Connect to the shared network
      - default # Keep default network for potential other service links if needed

networks:
  monitoring_net:
    external: true # Specify that this network is created elsewhere