global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s
      api_version: v2

scrape_configs:
  # --- KEEP THIS JOB ---
  # Scrapes the Spring Boot Actuator endpoint
  - job_name: spring_boot_app_metrics
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /actuator/prometheus # Correct path for Actuator
    scheme: http
    static_configs:
      - targets:
          - app:9087 # Correct port for Actuator (matches server.port)

